feat: Add default home page setting for routing
uni-helper/vite-plugin-uni-pages pull request #81
Opened 2023-05-11 08:23 UTC by Ares-Chang

Hi: 

我在使用中发现，如果我的 pages.config.ts 文件中 pages 字段如果不设置 type: 'home' ，并且恰巧有一个文件名在 index.vue 排序之前的文件。

我的路由就会生成如下情况：

![image](https://github.com/uni-helper/vite-plugin-uni-pages/assets/36911513/1cff5981-e4dd-4112-951c-33da3834202c)

index.vue 失去了默认主页设置。虽然设置 type: 'home' 可以解决，但是我觉得这个地方应该可以添加一个默认 index 或 index/index 默认路由。

所以我提交了这个 pr。

2023-05-11 08:26 UTC, Ares-Chang commented
sorry，因为不会使用 vitest ，并且运行测试报错了，所以没有添加 test。

2023-05-11 08:36 UTC, KeJunMao commented
很棒呀，起初想到的是用 route block 的 type 属性来指定第一项，默认有一个 index 话确实挺好的！

2023-05-11 08:55 UTC, KeJunMao requested changes

2023-05-11 08:55 UTC, KeJunMao commented on packages/core/src/context.ts
> +      if (!['index', 'index/index'].includes(path))
这里好像不太对?，`test/index.vue` 这种， 或许可以加个配置项然后直接把 `index.[n]vue, index/index.[nu]vue` 作为默认值

2023-05-11 08:55 UTC, KeJunMao commented on packages/core/src/context.ts
> +    const isHome = result.some((page) => {
hasHome

2023-05-11 09:34 UTC, Ares-Chang commented on packages/core/src/context.ts
> +      if (!['index', 'index/index'].includes(path))
`test/index` 并不符合要求，所以无法被更改。

一开始我也想要在 UniPages 注册的时候，设置个配置来着，但是我发现我好像不是很会，所以先选择了这种方式。

我可能得学习一下，可能需要一些时间。

2023-05-11 09:36 UTC, Ares-Chang commented on packages/core/src/context.ts
> +    const isHome = result.some((page) => {
ok

2023-05-12 01:55 UTC, merged

2023-05-12 06:40 UTC, Ares-Chang commented
thanks

2023-05-12 07:09 UTC, zguolee commented on packages/core/src/options.ts
> +    homePage = ['pages/index', 'pages/index/index'],
已经设置 `dir` 的前提下，这个主页路径是不是就不需要包含 `pages`了？

2023-05-12 08:05 UTC, KeJunMao commented on packages/core/src/options.ts
> +    homePage = ['pages/index', 'pages/index/index'],
俺不知道，应该有了吧？忘了